// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OtpVerification.Api.Data;

#nullable disable

namespace OtpVerification.Api.Migrations
{
    [DbContext(typeof(OtpDbContext))]
    [Migration("20250212180242_AddOneTimePin")]
    partial class AddOneTimePin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OtpVerification.Api.Data.Entities.OneTimePin", b =>
                {
                    b.Property<int>("OneTimePinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OneTimePinId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("RequestCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("OneTimePinId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("OneTimePins", (string)null);
                });

            modelBuilder.Entity("OtpVerification.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("LastIssuedOtpId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LastIssuedOtpId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("OtpVerification.Api.Data.Entities.OneTimePin", b =>
                {
                    b.HasOne("OtpVerification.Api.Data.Entities.User", "User")
                        .WithMany("OneTimePins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OtpVerification.Api.Data.Entities.User", b =>
                {
                    b.HasOne("OtpVerification.Api.Data.Entities.OneTimePin", "LastIssuedOtp")
                        .WithOne()
                        .HasForeignKey("OtpVerification.Api.Data.Entities.User", "LastIssuedOtpId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastIssuedOtp");
                });

            modelBuilder.Entity("OtpVerification.Api.Data.Entities.User", b =>
                {
                    b.Navigation("OneTimePins");
                });
#pragma warning restore 612, 618
        }
    }
}
